apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: roboshop
  name: replica-demo
  labels:
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      project: roboshop
      purpose: replicaset-demo
  template:
    metadata:
     labels:
      project: roboshop
      purpose: replicaset-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest

---

apiVersion: v1
kind: Service
metadata:
  name: service-demo 
  namespace: roboshop
   
spec:  
  type: LoadBalancer
  selector:

    project: roboshop
    purpose: replicaset-demo
  ports:
    - protocol: TCP
      port: 80 #servicePort
      targetPort: 80 #containerport