apiVersion: apps/v1
kind: Deployment
metadata:
  name: replica-demo
  labels:
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      purpose: replicaset-demo
  template:
    metadata:
     labels:
      project: roboshop
      purpose: replicaset-demo
    spec:
      containers:
        - name: nginx
          image: nginx:latest